### ISSUE TITLE
I want a warning logged when I have a typo in my `value` configuration

### ISSUE THREAD

**Issue by hansmosh** [nio-blocks/join#16]
I have a `value` configuration where the expression is trying to access an attribute on a signal where that attribute doesn't actually exist. This is resulting in no output from the block but also no warning logs.

Version of block: e2f01fc940225305013f9eb938a516c9308af8a3

**Comment by hansmosh** [comment]
```
>>> import nio
>>> nio.__version__
'2.0.0b5'
>>> import niocore
>>> niocore.__binary_build__
'20160503'
```

**Comment by tyoungNIO** [comment]
If `value` (or `key` for that matter) fails to evaluate, such as a signal attribute does not exist, an `AttributeError` should be logged. I have tested with the current release  of the block and cannot reproduce this issue, I am seeing the correct behavior in all cases:
`AttributeError: 'Signal' object has no attribute 'value'`
